version: 2.1
jobs:
  mobsfscan:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      #pwd is /home/circleci/project
      - run:
          name: Install mobsfscan
          command: pip install --upgrade mobsfscan
      - run:
           name: mobsfscan check
           command: mobsfscan src/ --output result
           #command: mobsfscan --output result src/ > /tmp/artifact-1;
           #command: mobsfscan --json -o results src/ > /tmp/artifact-1;
           #command: |
            #  mkdir /tmp/artifacts;
             # mobsfscan --output result src/ > /tmp/artifact-1;
           #command: |
            #  mkdir /tmp/artifacts;
             # echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      #- store_artifacts:
       #    path: /tmp/artifacts


workflows:
  mobsf-workflow:
    jobs:
      - mobsfscan
