version: 2.1
jobs:
  mobsfscan:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      #pwd is /home/circleci/project
      - run:
          name: Install mobsfscan
          command: pip install --upgrade mobsfscan
      - run:
           name: mobsfscan check
           #command: mobsfscan src/
           command: mobsfscan -o results src/
           #command: mobsfscan --json -o results src/ > /tmp/artifact-1;
      #- store_artifacts:
       #    path: /tmp/artifact-1
        #   destination: artifact-file
      #- store_artifacts:
       #    path: /tmp/artifacts


workflows:
  mobsf-workflow:
    jobs:
      - mobsfscan
