version: 2.1
jobs:
  mobsfscan:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install mobsfscan
          command: pip install --upgrade mobsfscan
      - run:
           name: mobsfscan check
           #command: mobsfscan src/
           command: mobsfscan --json -o results.json src/

workflows:
  mobsf-workflow:
    jobs:
      - mobsfscan
